<<<<<<< HEAD
env:
  global:
    - CC_TEST_REPORTER_ID=$CODECLIMATE_REPO_TOKEN
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: node_js
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - bundle exec rspec
  # Preferably you will run test-reporter on branch update events. But
  # if you setup travis to build PR updates only, you don't need to run
  # the line below
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
  # In the case where travis is setup to build PR updates only,
  # uncomment the line below
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
node_js:
  - node
=======
language: node_js
node_js:
  - node
env:
  - TEST_DIR=server
>>>>>>> ad44c0c7b60423889f2e4e3e79b032885217e1d8
notifications:
  email: false
services:
  - postgresql
before_script:
<<<<<<< HEAD
  - npm install -g codeclimate-test-reporter
  - npm install -g sequelize
  - psql -c 'drop database if exists testdb;' -U postgres
  - psql -c 'create database testdb;' -U postgres
  - psql -c "CREATE USER ekundayo WITH PASSWORD 'ekundayo';" -U postgres
=======
  - cd $TEST_DIR && npm install && npm install -g codeclimate-test-reporter
  - npm install -g sequelize
  - psql -c 'drop database if exists travis;' -U postgres
  - psql -c 'create database travis;' -U postgres
  - npm run build
>>>>>>> ad44c0c7b60423889f2e4e3e79b032885217e1d8
  - NODE_ENV=test npm run test:db
script:
  - npm test
after_success:
<<<<<<< HEAD
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
=======
  - -npm run coverage
  - CODECLIMATE_REPO_TOKEN=CODECLIMATE_TOKEN codeclimate-test-reporter < coverage/lcov.info
>>>>>>> ad44c0c7b60423889f2e4e3e79b032885217e1d8
  - coveralls < coverage/lcov.info